doctrine:
    dbal:
        server_version: '8'
        url: '%env(resolve:DATABASE_URL)%'
        user: root
        password: easy123

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
