version: '3'

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - parkhaus_network

  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: easy123
      MYSQL_DATABASE: parkhaus
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3306'
    networks:
      - parkhaus_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    networks:
      - parkhaus_network

volumes:
  dbdata:

networks:
  parkhaus_network:
    driver: bridge